portal_forum/main/routes.py
import sys
from datetime import datetime

from flask import Blueprint, flash, redirect, abort, request
from flask import render_template, url_for
from sqlalchemy import desc

from portal_forum import db
from portal_forum.models import Thread, Album, Track
from flask_login import current_user, login_required
from portal_forum.users.utils import check_image
from portal_forum.main.forms import AlbumForm

main = Blueprint('main', __name__)

def check_image():
    if current_user.is_authenticated:
        return url_for('static', filename='profile_pics/' + current_user.image_file)
    else:
        return "none"

@main.route('/')
@main.route('/home')
def home():
    return render_template('portal-home.html')

@main.route('/forum')
def forum():
    threads = Thread.query.order_by(desc(Thread.date_last_update)).limit(5).all()
    tracks = Track.query.order_by(desc(Track.date_last_update)).limit(5).all()
    return render_template('forum-home.html', image_file=check_image(), threads=threads, tracks=tracks)

@main.route('/admin_panel', methods=['GET','POST'])
@login_required
def admin_panel():
    if not current_user.is_admin:
        abort(403)
    albums = Album.query.all()
    return render_template('admin_panel.html', image_file=check_image(), title="Panel administracyjny", albums=albums)

@main.route('/album//create', methods=['GET','POST'])
@login_required
def create_album():
    if not current_user.is_admin:
        abort(403)
    form = AlbumForm()
    if form.validate_on_submit():
        year = int(datetime.utcnow().year)
        print("_____________________________________________________-", file=sys.stderr)
        print(year, file=sys.stderr)
        print("_____________________________________________________", file=sys.stderr)
        album = Album(title=form.title.data, date_release=form.date_release.data, description=form.description.data)
        db.session.add(album)
        db.session.commit()
        flash('Album dodano pomyślnie!', 'success')
        return redirect(url_for('main.admin_panel'))
    return render_template('create_album.html', title="Dodaj album",
                           form=form, image_file=check_image())

@main.route('/album/<int:album_id>/update', methods=['GET','POST'])
@login_required
def update_album(album_id):
    if not current_user.is_admin:
        abort(403)
    album = Album.query.get_or_404(album_id)
    form = AlbumForm()
    if form.validate_on_submit():
        album.title = form.title.data
        album.date_release = form.date_release.data
        album.description = form.description.data
        db.session.commit()
        flash("Album został zaktualizowany!", 'success')
        return redirect(url_for('main.admin_panel'))
    elif request.method == "GET":
        form.title.data = album.title
        form.description.data = album.description
        form.date_release.data = album.date_release
    return render_template('create_album.html', title="Edytuj album",
                           form=form, image_file=check_image())
@main.route('/album/<int:album_id>/delete', methods=['POST','GET'])
@login_required
def delete_album(album_id):
    if not current_user.is_admin:
        abort(403)
    album = Album.query.get_or_404(album_id)
    db.session.delete(album)
    db.session.commit()
    flash("Album usunięty", 'success')
    return redirect(url_for('main.admin_panel'))

portal_forum/user_activity/routes.py
import sys
from functools import wraps

from flask import render_template, url_for, redirect, flash, request, abort, Blueprint, g, json
from markupsafe import Markup
from sqlalchemy import desc, asc
from portal_forum.user_activity.forms import ThreadForm, PostForm, TrackForm, ScrapForm
from portal_forum import db
from portal_forum.models import Thread, User, Thread_Post, Track, Album, Scrap, Track_Post, Interpretation
from flask_login import login_user, current_user, logout_user, login_required
from datetime import datetime
from portal_forum.users.utils import check_image
import re

user_activity = Blueprint('user_activity', __name__)


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_authenticated:
            return redirect(url_for('users.login', next=request.url))
        return f(*args, **kwargs)

    return decorated_function


def check_image():
    if current_user.is_authenticated:
        return url_for('static', filename='profile_pics/' + current_user.image_file)
    else:
        return "none"


@user_activity.route('/threads', methods=['GET', 'POST'])
def threads():
    strona = request.args.get('strona', 1, type=int)
    threads = Thread.query.order_by(desc(Thread.date_last_update)).paginate(page=strona, per_page=5)
    return render_template('threads.html', title="Wątki", image_file=check_image(), threads=threads)


@user_activity.route('/thread/<int:thread_id>', methods=['GET', 'POST'])
def thread(thread_id):
    thread = Thread.query.get_or_404(thread_id)
    tags = Markup(thread.description)
    posts = Thread_Post.query. \
        filter_by(thread=thread). \
        order_by(asc(Thread_Post.date_posted))
    replies = []
    for post in posts:
        replies.append(Markup(post.reply))
    return render_template('thread.html', title=thread.topic, image_file=check_image(), thread=thread, tags=tags,
                           posts=posts, replies=replies)


@user_activity.route('/thread/new', methods=['GET', 'POST'])
@login_required
def new_thread():
    form = ThreadForm()
    if form.validate_on_submit():
        thread = Thread(topic=form.topic.data, description=form.description.data, author=current_user)
        db.session.add(thread)
        db.session.commit()
        flash("Wątek został dodany", "success")
        return redirect(url_for('main.forum'))
    return render_template('create_thread.html', title="Nowy wątek",
                           legend="Rozpocznij nowy wątek", form=form, image_file=check_image())


@user_activity.route('/thread/<int:thread_id>/update', methods=['GET', 'POST'])
@login_required
def update_thread(thread_id):
    thread = Thread.query.get_or_404(thread_id)
    if thread.author != current_user:
        abort(403)
    form = ThreadForm()
    if form.validate_on_submit():
        thread.topic = form.topic.data
        thread.description = form.description.data
        thread.date_last_update = datetime.strptime(str(datetime.utcnow()), "%Y-%m-%d %H:%M:%S.%f")
        db.session.commit()
        flash("Wątek zaktualizowany!", 'success')
        return redirect(url_for('user_activity.thread', thread_id=thread.id))
    elif request.method == "GET":
        form.topic.data = thread.topic
        form.description.data = thread.description
    return render_template('create_thread.html', title="Edytuj wątek",
                           legend="Edytuj wątek", form=form, image_file=check_image(), thread_id=thread_id)


@user_activity.route('/thread/<int:thread_id>/delete', methods=['POST'])
@login_required
def delete_thread(thread_id):
    thread = Thread.query.get_or_404(thread_id)
    if thread.author != current_user and not current_user.is_admin:
        abort(403)
    db.session.delete(thread)
    db.session.commit()
    flash("Wątek usunięty", 'success')
    return redirect(url_for('main.forum', thread_id=thread.id))


@user_activity.route('/thread/<int:thread_id>/reply', methods=['GET', 'POST'])
@login_required
def thread_reply(thread_id):
    form = PostForm()
    if form.validate_on_submit():
        post = Thread_Post(reply=form.reply.data, author=current_user, thread_id=thread_id)
        db.session.add(post)
        db.session.commit()
        flash("Odpowiedź została dodana", "success")
        return redirect(url_for('user_activity.thread', thread_id=thread_id))
    return render_template('thread_reply.html', title="Rozwiń wątek",
                           legend="Odpowiedz", form=form, image_file=check_image(),
                           thread_id=thread_id, reply_id=None)


@user_activity.route('/thread/<int:thread_id>/reply_to/<int:post_id>', methods=['GET', 'POST'])
@login_required
def quote_thread_post(thread_id, post_id):
    post = Thread_Post.query.get_or_404(post_id)
    form = PostForm()
    date_posted = str(datetime.strptime(str(post.date_posted), "%Y-%m-%d %H:%M:%S.%f"))
    date_posted = date_posted.split(".")[0]
    quote = "<div>" \
            "<div style='background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;'>" \
            "<b>" + post.author.username + "</b> powiedział " + date_posted + \
            "</div>" \
            "<blockquote class='cke_contents_ltr blockquote'>" + post.reply + "</blockquote>" \
                                                                              "<p></p></div>"
    if form.validate_on_submit():
        post = Thread_Post(reply=form.reply.data, author=current_user, thread_id=thread_id)
        db.session.add(post)
        db.session.commit()
        flash("Odpowiedź została dodana", "success")
        return redirect(url_for('user_activity.thread', thread_id=thread_id))
    elif request.method == "GET":
        form.reply.data = Markup(quote)
    return render_template('thread_reply.html', title="Rozwiń wątek",
                           legend="Odpowiedz użytkownikowi " + post.author.username, form=form,
                           image_file=check_image(),
                           thread_id=thread_id, reply_id=None)


@user_activity.route('/thread/<int:thread_id>/reply/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_thread_post(post_id, thread_id):
    thread = Thread.query.get_or_404(thread_id)
    post = Thread_Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.reply = form.reply.data
        post.date_last_update = datetime.strptime(str(datetime.utcnow()), "%Y-%m-%d %H:%M:%S.%f")
        db.session.commit()
        flash("Odpowiedź została zaktualizowana!", 'success')
        return redirect(url_for('user_activity.thread', thread_id=thread.id))
    elif request.method == "GET":
        form.reply.data = post.reply
    return render_template('thread_reply.html', title="Edytuj odpowiedź",
                           legend="Edytuj odpowiedź", form=form,
                           image_file=check_image(),thread_id=thread.id)


@user_activity.route('/thread/<int:thread_id>/reply/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_thread_post(thread_id, post_id):
    thread = Thread.query.get_or_404(thread_id)
    post = Thread_Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Odpowiedź została usunięta", 'success')
    return redirect(url_for('user_activity.thread', thread_id=thread.id))


@login_required
@user_activity.route('/track/<int:track_id>', methods=['GET', 'POST'])
def track(track_id):
    track = Track.query.get_or_404(track_id)
    tags = Markup(track.lyrics)
    comments = Track_Post.query. \
        filter_by(track=track). \
        order_by(asc(Track_Post.date_posted))
    tags_description = Markup(track.description)

    replies = []
    for comment in comments:
        replies.append(Markup(comment.reply))

    return render_template('track.html', title=track.title, image_file=check_image(), track=track, tags=tags,
                           tags_description=tags_description, comments=comments, replies=replies)


@user_activity.route('/tracks', methods=['GET', 'POST'])
@login_required
def tracks():
    strona = request.args.get('strona', 1, type=int)
    tracks = Track.query.order_by(desc(Track.date_last_update)).paginate(page=strona, per_page=5)
    return render_template('tracks.html', title="Utwory", image_file=check_image(), tracks=tracks)


@user_activity.route('/tracks/new', methods=['GET', 'POST'])
@login_required
def new_track():
    form = TrackForm()
    albums = Album.query.all()

    if form.validate_on_submit():
        albums_list = request.form.getlist("albums")
        tags = form.lyrics.data
        tags = tags.replace("<p>", '')
        tags = tags.replace("</p>", "<br/>")
        track = Track(title=form.title.data, lyrics=tags, lyrics_with_scraps=tags, author=current_user,
                      date_release=form.date_release.data, lyrics_by=form.lyrics_by.data,
                      description=form.description.data)

        for cd in albums_list:
            album = Album.query.filter_by(id=int(cd)).first_or_404()

            track.albums.append(album)
        db.session.add(track)
        db.session.commit()

        db.session.commit()
        flash("Utwór został dodany", "success")
        return redirect(url_for('user_activity.tracks'))

    return render_template('create_track.html', title="Nowy Utwór", albums=albums,
                           legend="Dodaj nowy utwór", form=form, image_file=check_image())


@user_activity.route('/track/<int:track_id>/update', methods=['GET', 'POST'])
@login_required
def update_track(track_id):
    track = Track.query.get_or_404(track_id)
    if track.author != current_user:
        abort(403)
    form = TrackForm()
    if form.validate_on_submit():
        tags = form.lyrics.data
        tags = tags.replace("<p>", '')
        tags = tags.replace("</p>", "<br/>")

        track.title = form.title.data

portal_forum/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, redirect, flash, request, g
from portal_forum.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from portal_forum import db, bcrypt
from portal_forum.models import User
from flask_login import login_user, current_user, logout_user, login_required
from portal_forum.users.utils import save_image, check_image
from functools import wraps

users = Blueprint('users', __name__)


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not current_user.is_authenticated:
            return redirect(url_for('users.login', next=request.url))
        return f(*args, **kwargs)

    return decorated_function

@users.route('/register', methods=['GET', 'POST'])
def register():
    if User.query.filter_by(is_admin=True).first() is None:
        hashed_password = bcrypt.generate_password_hash("admin123").decode('utf-8')
        admin = User(username="Admin", email="true.admin@mail.com", password=hashed_password, is_admin=True)
        db.session.add(admin)
        db.session.commit()
    if current_user.is_authenticated:
        return redirect(url_for('main.forum'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, is_admin=False)
        db.session.add(user)
        db.session.commit()
        flash('Twoje konto utworzono pomyślnie!', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title="Rejestracja", form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.forum'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.forum'))
        else:
            flash('Wprowadzono niepoprawne dane', 'danger')
    return render_template('login.html', title="Logowanie", form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.forum'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            image_file = save_image(form.picture.data)
            current_user.image_file = image_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Twoje dane zostały zaktualizowane', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title="Konto użytkownika", image_file=image_file, form=form)

portal_forum/templates/forum-home.html
{% extends "forum-layout.html" %}
{% block content %}
    <div class="card">
        <div class="card-header">
            Ostatnia aktywność
        </div>
        <div class="card-body">
            <table class="table">
                <thead class="thead-primary">
                <tr>
                    <th scope="col">Data</th>
                    <th scope="col">Autor</th>
                    <th scope="col">Temat</th>
                    <th scope="col" class="hide-mobile">Odpowiedzi</th>
                    <th scope="col" class="hide-mobile">Odsłony</th>
                    <th scope="col" class="hide-mobile">Ostatnia aktualizacja</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for thread in threads %}
                    <tr>
                        <td>{{ thread.date_posted.strftime('%Y-%m-%d %H:%M') }}</td>
                        <td>{{ thread.author.username }}</td>
                        <td>{{ thread.topic }}</td>
                        <td class="hide-mobile">odpowiedzi</td>
                        <td class="hide-mobile">odsłony</td>
                        <td class="hide-mobile">{{ thread.date_last_update.strftime('%Y-%m-%d %H:%M') }}</td>
                        <td><a href="{{ url_for('user_activity.thread', thread_id=thread.id) }}"
                               class="btn bg-dark text-white">Przejdź >></a></td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>

            <a href="{{ url_for("user_activity.threads") }}"
               class="btn bg-dark text-white responsive-full responsive-marg-6">Zobacz wszystkie wątki</a>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for("user_activity.new_thread") }}" class="btn bg-dark text-white responsive-full">
                    <svg xmlns="url_for('static', filename='/images/plus-circle.svg/')" width="20" height="20"
                         fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                    </svg>
                    Rozpocznij nowy wątek
                </a>
            {% endif %}
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            Utwory Toma Waitsa
        </div>
        {% if current_user.is_authenticated %}
            <div class="card-body">
                <table class="table">
                    <thead class="thead-primary">
                    <tr>
                        <th scope="col">Dodano</th>
                        <th scope="col">Tytuł</th>
                        <th scope="col">Albumy</th>

                        <th scope="col" class="hide-mobile">Odpowiedzi</th>
                        <th scope="col" class="hide-mobile">Odsłony</th>
                        <th scope="col" class="hide-mobile">Ostatnia aktualizacja</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for track in tracks %}
                        <tr>
                            <td>{{ track.date_posted.strftime('%Y-%m-%d %H:%M') }}</td>
                            <td>{{ track.title }}</td>
                            <td>
                                {% for album in track.albums %}
                                    {% if loop.index < track.albums|length %}
                                        {{ album.title }},
                                    {% else %}
                                        {{ album.title }}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td class="hide-mobile">odpowiedzi</td>
                            <td class="hide-mobile">odsłony</td>
                            <td class="hide-mobile">{{ track.date_last_update.strftime('%Y-%m-%d %H:%M') }}</td>
                            <td><a href="{{ url_for('user_activity.track', track_id=track.id) }}" class="btn bg-dark text-white">Przejdź >></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <a href="{{ url_for("user_activity.tracks") }}" class="btn bg-dark text-white responsive-full responsive-marg-6">Zobacz wszystkie utwory</a>
                <a href="{{ url_for("user_activity.new_track") }}" class="btn bg-dark text-white responsive-full">
                    <svg xmlns="url_for('static', filename='/images/plus-circle.svg/')" width="20" height="20"
                         fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                    </svg>
                    Dodaj nowy utwór
                </a>
            </div>
        {% else %}
            <div class="card-body">
                <h5 class="card-title">Dyskusje o utworach</h5>
                <p class="card-text"><a href="{{ url_for("users.login") }}" class="grey-link">Zaloguj się</a> lub <a
                        class="grey-link" href="{{ url_for("users.register") }}">zarejestruj</a>, żeby brać udział w
                    dyskusjach.</p>
            </div>
        {% endif %}
    </div>

{% endblock content %}

portal_forum/templates/forum-layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	{% if title %}
        <title>{{title}}</title>
    {% else %}
        <title>Tom Waits Forum</title>
    {%endif%}

	<!-- jQuery -->
<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
crossorigin="anonymous"></script>

<!-- Bootstrap files (jQuery first, then Popper.js, then Bootstrap JS) -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">
	</head>
<body>
	<div class="container">
  <!-- Content here -->
		<header class="section-header py-4">
	<div class="container-logo">
            <a class="no-style-link" href="{{ url_for("main.forum") }}">
                <h1>Tom Waits - Forum</h1>
		        <p>Zrozumieć poetę</p>
            </a>
	</div>
	</header> <!-- section-header.// -->
		<nav class="navbar navbar-dark bg-primary bg-dark text-white navbar-expand-lg">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarTogglerDemo01">

				<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
					<li class="nav-item active">
						<a class="nav-link wh-brd-right" href="{{ url_for("main.forum") }}">Strona główna <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/threads">Wątki</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/tracks">Utwory</a>
					</li>

				</ul>
				<ul class="navbar-nav my-2 my-md-0">

                    {% if current_user.is_authenticated %}

                        <li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" style="padding-bottom: 0;padding-top: 0;" href="#" data-toggle="dropdown">
                            <img class="rounded-circle account-img" width="50" height="50" src="{{ image_file }}">
                            {{ current_user.username }}
                        </a>
						<ul class="dropdown-menu">
							<li><a class="dropdown-item btn-secondary" href="{{ url_for("users.account") }}"> Konto </a></li>
                            {% if current_user.is_admin %}
                            <li><a class="dropdown-item btn-secondary" href="{{ url_for("main.admin_panel") }}"> Panel administracyjny </a></li>
                            {% endif %}
                            <li><div class="dropdown-divider"></div></li>
							<li><a class="dropdown-item btn-secondary" href="{{ url_for("users.logout") }}"> Wyloguj </a></li>
						</ul>
					</li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for("users.login") }}"><button class="btn bg-light text-dark my-2 my-sm-0 responsive-full" type="submit">Zaloguj się</button></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for("users.register") }}"><button class="btn bg-light text-dark my-2 my-sm-0 responsive-full" type="submit">Zarejestruj się</button></a>
                        </li>
                    {% endif %}
                        <li class="nav-item active text-middle-height">
                            <a class="nav-link hv-back-grey responsive-full" href="{{ url_for("main.home") }}"><b>Portal</b><span class="sr-only">(current)</span></a>
                        </li>
				</ul>
			</div>
		</nav>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                    {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    <div id="content">
        {%block content%}{%endblock%}
    </div>


	</div>

  </body>
</html>

portal_forum/templates/track_reply.html
{% extends "forum-layout.html" %}
{% block content %}
    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>

    <div class="content-section">
            <form method="POST">
                {{ form.hidden_tag() }}
               <fieldset class="form-group">
                    <legend class="mb-4">{{ legend }}</legend>
                    <div class="form-group">
                        {% if form.reply.errors %}
                            {{ form.reply(class="form-control form-control-lg is-invalid", name="reply", id="reply") }}
                            <div class="invalid-feedback">
                                {% for error in form.reply.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.reply(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <script>
                        CKEDITOR.replace( 'reply' );
                    </script>
                </fieldset>
                <div class="form-group">
                        <button type="submit" class="btn bg-dark text-white">Zapisz</button>
                        <a href="{{ url_for('user_activity.track', track_id=track_id) }}" class="btn bg-dark text-white responsive-full">Powrót</a>
                </div>
            </form>
    </div>
{% endblock content %}